name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install and Build
      run: |
        cd github-actions-demo
        npm install
        npm build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: github-actions-demo/build
        token: ${{ secrets.ACCESS_TOKEN }}
      #env:
        #ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        #BRANCH: gh-pages
        #FOLDER: build
        #BUILD_SCRIPT: npm install && npm run build
