name: GitHub Actions Test
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install packages
      run: apt install -y npm
      
    - name: Install and Build
      working-directory: ./github-actions-demo
      run: |
        npm install
        npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: github-actions-demo/build
        target-folder: github-actions-demo
        token: ${{ secrets.ACCESS_TOKEN }}
